### ISSUE TITLE
Badge proposal: Spoed Toeter - Proposed

### ISSUE THREAD

**Issue by Potherca** [DealerDirect/Achievements#259]
I would like to propose a new badge: [Spoed Toeter](http://sd.keepcalm-o-matic.co.uk/i-w600/spoedtoeter-fastlane-issue.jpg)
So we can award a person a badge when they step up to fix a fast-lane issue.

Badge image: 
![badge_toeter](https://cloud.githubusercontent.com/assets/195757/20786667/9f4b19fa-b7a7-11e6-87f6-566f724c9c6e.png)

Can I get a vote yay/nay for all of those eligible to vote?

| Developer | Yay | Nay |
| --- | --- | --- |
| @arjank |  |  |
| @brammittendorff-dd | :ballot_box_with_check: |  |
| @Dravenshorst | :ballot_box_with_check: |  |
| @eaulav |  |  |
| @edvance |  |  :ballot_box_with_check:  |
| @Marascon | :ballot_box_with_check:  |  |
| @mjbakker |  |  |
| @pimkaptein | :ballot_box_with_check: |  |
| @potherca | :ballot_box_with_check: |  |
| @Terrub |  |  |
| @wouteroostervld |  |  |
| Total = 11 | 5 | 1 |

**Comment by hipio** [comment]
External vote: ☑️

**Comment by Marascon** [comment]
YAY

**Comment by MaaikeRonhaar** [comment]
yAy

**Comment by brammittendorff-dd** [comment]
yay

**Comment by edvance** [comment]
nay. The name is a bit confusion for the work someone is doing and if
someone has time and another not, he could get a button, just for having
time for this. Shouldn't this be something special, or are we making
putting your cup in the dishwasher badges too because we are happy about
that? I know that is a somewhat simple example but hope you catch the drift.

On Mon, Dec 12, 2016 at 11:54 AM, Bram Mittendorff <notifications@github.com

**Comment by Potherca** [comment]
I think @edvance raises a valud concern. There was a discussion to add this badge to the Meme's repo rather than here. I find it hard to put my finger on it but adding the badge here does feel slightly beyond the scope of this repo.

I'm Considering retrackting this proposal.

**Comment by Potherca** [comment]
Closing due to lack of interest. Badge will be available in the Meme repo instead.
